apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market
  template:
    metadata:
      labels:
        app: market
    spec:
      containers:
        - name: market
          image: mohamedemad1/market
          env:
            - name: MONGO_URI
              value: mongodb://market-mongo-cluster-ip-service:27017/market
            - name: CLOUDINARY_NAME
              value: micro-services
            - name: CLOUDINARY_API_KEY
              value: "467668724553657"
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-api-secret-social
                  key: CLOUDINARY_API_SECRET

