apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-mongo
  template:
    metadata:
      labels:
        app: market-mongo
    spec:
      containers:
        - name: market-mongo
          image: mongo
