apiVersion: v1
kind: Service
metadata:
  name: order-mongo-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: order-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017