apiVersion: v1
kind: Service
metadata:
  name: order-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - name: order
      protocol: TCP
      port: 3000
      targetPort: 3000
