apiVersion: v1
kind: Service
metadata:
  name: payment-mongo-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: payment-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017