apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-mongo
  template:
    metadata:
      labels:
        app: payment-mongo
    spec:
      containers:
        - name: payment-mongo
          image: mongo
