apiVersion: v1
kind: Service
metadata:
  name: payment-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - name: payment
      protocol: TCP
      port: 3000
      targetPort: 3000
