apiVersion: v1
kind: Service
metadata:
  name: reply-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: reply
  ports:
    - name: reply
      protocol: TCP
      port: 3000
      targetPort: 3000
